### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by grawlinson** [t3mujin/t3mujinpack#1]
It's beneficial if you add a license to this project, as it removes licensing ambiguities.

Check out the various open source licenses [here](https://opensource.org/licenses), as well as the [Creative Commons licenses](https://creativecommons.org/choose/).

**Comment by t3mujin** [comment]
Thanks @grawlinson, you're right. I'll add that and set the project to a MIT licence just before releasing the upcoming version.
