### ISSUE TITLE
Hierarchical view

### ISSUE THREAD

**Issue by t3mujin** [t3mujin/t3mujinpack#11]
Add a hierarchical view to organize the styles, based on the new view on darktable 2.6.1

Thread to discuss hierarchy formats:
https://discuss.pixls.us/t/poll-t3mujinpack-with-hierarchical-view/11809?u=t3mujin

**Comment by Fale** [comment]
I think this one could be closed, since that's already the case

**Comment by t3mujin** [comment]
@Fale true! I didn't close it at the time because I still wasn't sure about the structure.
