### ISSUE TITLE
Coloured films should apply channelmixers profile

### ISSUE THREAD

**Issue by Fale** [t3mujin/t3mujinpack#12]
Hi, very nice project!

I've noticed that - among other things - the b/w films styles apply a channelmixer option, while the coloured films styles do not.
This means that if you take rawfile created with b/w in-camera options, the coloured films do not apply (the are not coloured) since the channelmixer option is still there.
I think this should be fixed at films style level, becuase my expectation (and I guess many others as well) is that applying a coloured film style to a raw file (no matter of the in-camera options) will output a coloured image.

**Comment by t3mujin** [comment]
@Fale you mean something like resetting the channelmixer when applying the color emulations? It's one of those things that never was the case for me, because I rarely switch between color and b&w, but I can see how annoying that can be.

**Comment by Fale** [comment]
Yes, I mean something like it!

**Comment by t3mujin** [comment]
Added to the color styles
