### ISSUE TITLE
sqlite version

### ISSUE THREAD

**Issue by PanPiotrAdamus** [t3mujin/t3mujinpack#13]
Hello,

on the Arch linux sqlite binary is sqlite3 `/usr/bin/sqlite3`. The current script to remove the styles will error out of the missing sqlite. Fix is to add:

`if [ ! -x "`which "sqlite3"`" ]`

instead of current

`if [ ! -x "`which "sqlite"`" ]`

This is it. 

Thanks :)

Piotr.

**Comment by t3mujin** [comment]
Cool, thanks for the feedback
