### ISSUE TITLE
Styles to 3D Luts for support with other Software?

### ISSUE THREAD

**Issue by paul-pw** [t3mujin/t3mujinpack#23]
How about in adition to providing the styles as Darktable Styles also providing them in a 3D Lut Format maybe in a special Lut release?
  
This way these amazing styles could not just be used in darktable but in any softwar that supports the use of 3D Luts (for example in Photoshop, Gimp, Raw Therapee and so on).  
Also for darktable users: Styles could be combined by using multiple 3DLut instances if needed.

It shouldn'd be hard to write a little Lua scipt that does this automaticaly.  
an other option would just be to apply the Styles to identity HaldCLUTs and export them as png. that then is the Lut in HaldClut format. Easy as that.
 
this is the identity HaldCLUT
![HaldCLUT_Identity](https://user-images.githubusercontent.com/58135819/79317194-b1a27700-7f05-11ea-8a94-ea3f7b78684f.png)

**Comment by t3mujin** [comment]
Hi! I never thought about that. I guess could add that to backlog! :)

**Comment by mjut** [comment]
What I really like about using LUTs is that I can see what preset I used. By looking at the LUTs name it is straight forward to see. 
With darktable styles, it is hart to determine the film emulation applied. Especially when reviewing older images.
@paul-pw  I never thought of applying any style to the identity HaldCLUT. I need to try this!

**Comment by noahwc** [comment]
+1 for the reasons already stated. Plus I feel like it would be easier to blend in styles if the whole adjustment is limited to a single module. Styles are nice as they can be tweaked on a per image basis but choice is even nicer 😄.

I have some spare time in the coming weeks and would be into taking a crack at this. I wonder if a bash script instead of a lua script might be better/easier given darktable-cli.

**Comment by mjut** [comment]
I just tried to generate a LUT by exporting a png via darktable. (Using that identity HaldCLUT) This generated png was faulty, e.g. I couldn't load it into the darktable LUT module.
I like the idea of using a script to do this. But I have no idea how to?

**Comment by noahwc** [comment]
I seem to have generated a working HaldCLUT for Fuji Neopan Acros 100 without issue.

Result from style being applied:
![matthias-koch-drXP4PAy2eo-unsplash_STYLE](https://user-images.githubusercontent.com/7761715/79515823-851e5600-7ffe-11ea-9c59-777ad79d7433.jpg)

Result from HaldCLUT being applied:
![matthias-koch-drXP4PAy2eo-unsplash_LUT](https://user-images.githubusercontent.com/7761715/79515807-7fc10b80-7ffe-11ea-9b89-583f3788a006.jpg)

The results do appear identical :smile: 

HaldClut
![Fuji_Neopan_Acros_100_HaldCLUT](https://user-images.githubusercontent.com/7761715/79515892-ada65000-7ffe-11ea-8822-a610c3d159d8.png)

@mjut I'm interested in why your attempt didn't work. 

After looking at the darktable documentation it appears as though while a bash script is the quick and dirty solution a lua script would be much more useful. My plan as of now is to create a lua script which allows any user style to be output as a HaldCLUT. This will take some extra time (especially with exams :cry:) but I think the end result will be worth it. If anyone has any input or feedback about this please let me know!

**Comment by noahwc** [comment]
After stumbling through learning some lua turns out script writing in darktable is actually fairly accessible. While the lua script still needs some polishing I was able to generate a set of luts from the styles pack and they seem to be working! These luts are quite large unfortunately at 1.4 MB per lut.

I've forked this repository and the luts can be found here: https://github.com/noahwc/t3mujinpack/tree/luts/haldcluts

**Comment by mjut** [comment]
Nice!
I got the LUTs working now! The issue: I loaded the new LUTs from a different location. Not the location that was set in Darktable's preferences. Darktable doesn't like that.. ;) 
After fixing that, everything is working as expected.
Thanks for providing the LUTs!!
 =)

**Comment by paul-pw** [comment]
>These luts are quite large unfortunately at 1.4 MB per lut.

that was to be expected since the Identity png also started out big (1728\*1728px) which results in a 144\*144\*144 lut  

it might be posible to use a smaler identity Lut e.g. using a 64\*64\*64 Lut which would turn out as a 512\*512px png image  
I don't know about the original HaldClut specification. it works with darktable, but I havent tested it in any other software. 

64*64*64 identity
![smal_identity](https://user-images.githubusercontent.com/58135819/79564725-7ba0f680-80af-11ea-9df5-fc2ab09629c2.png)

**Comment by paul-pw** [comment]
in my experience it also makes a difference wether the Lut is on top of or under the base curve, I get the closest result to the original style when moving the Lut on top of the base curve.  
By default the Lut is under the base curve in darktable

**Comment by noahwc** [comment]
> And maybe you would see some differences between the original Style and the Lut if you would use a smaler Lut

Using a smaller identity lut is a good idea, I'll do some tests with various sizes of identities over the next few days. I wonder if the ability to select the lut interpolation method in darktable will be useful here?

> in my experience it also makes a difference wether the Lut is on top of or under the base curve, I get the closest result to the original style when moving the Lut on top of the base curve.
By default the Lut is under the base curve in darktable

Good point, I hadn't encountered this as I had been testing with jpg/tif files which don't have a base curve applied. I suppose if the decision is made to include luts in the official style pack that bit of info should be added to the readme.

**Comment by t3mujin** [comment]
You stop paying attention to your issues for a day and things go "out of control" :) Very nice to catch up this discussion.

**Comment by noahwc** [comment]
For a visual reference of what @paul-pw mentioned here is an image with the Portra 160 style applied:

![IMG_3472_style](https://user-images.githubusercontent.com/7761715/79680280-decf7d80-81c2-11ea-888b-bece0df7ab21.jpg)

With the lut applied and the default pixel pipe order, notice the rather ugly colour on the house:

![IMG_3472_lut](https://user-images.githubusercontent.com/7761715/79680287-f0188a00-81c2-11ea-98ab-251ef52f24ba.jpg)

With the lut applied and the lut 3D module moved to after the filmic module (which is effectively a base curve):

![IMG_3472_lut_after_filmic](https://user-images.githubusercontent.com/7761715/79680303-26eea000-81c3-11ea-93bd-64c43b9752e0.jpg)

Unfortunately I don't have a strong enough understanding of how the pixel pipe works to know if moving lut 3D to after base curve / filmic is a "dangerous" operation. It does give good results with the luts generated from this style pack though!

**Comment by t3mujin** [comment]
I don't really know the pipeline that much to give a valid opinion, but putting the lut3d module after filmic or base curve does make sense, at least in theory.  Even so, from my testing most of the times looks just fine, so clearly is an edge case, possibly related with highlights reconstruction or exposure (often with filmic I have to compensate exposure after doing adjustments due to highlights issues).

**Comment by phweyland** [comment]
> that was to be expected since the Identity png also started out big (1728*1728px) which results in a 144*144*144 lut

G'MIC luts are limited to 48x48x48 if I'm not mistaken. Over this you should not see any difference. Also cube lut are often limited to 33x33x33. dt won't work above 255x255x255.







> I don't really know the pipeline that much to give a valid opinion, but putting the lut3d module after filmic or base curve does make sense, at least in theory.

Between 

> I don't really know the pipeline that much to give a valid opinion, but putting the lut3d module after filmic or base curve does make sense, at least in theory.

Between input and output module, lut3d let you choose the color space and makes the necessary conversions. Normally you should select the one for which this lut has been built.
Outside, it uses the rgb values as they are.
