### ISSUE TITLE
Color Mixer deprecated

### ISSUE THREAD

**Issue by Mathys-Rituper** [t3mujin/t3mujinpack#29]
The channel mixer module is now deprecated in darktable due to the software switching to the new scene-related workflow, effectively disabling all color changes and leaving us only with the tonal adjustments.One could say that it basically ruins the whole point of these presets if color changes are lost.
Are you planning on updating the preset pack to fit for the new workflows ?

**Comment by t3mujin** [comment]
Hi! Basically yes, specially for b&w films that rely on channel mixer a lot (#26 and #26) but honestly I don't have an estimate for doing that... I was trying to aim before the next version, mas it's only one month away.

Closing this one, as it's a duplicate for the other two issues.

Thanks!
