### ISSUE TITLE
file name issue on Windows

### ISSUE THREAD

**Issue by xarthurx** [t3mujin/t3mujinpack#30]
Hello, thank you for developing the pack, firstly.

I'm on Windows, and when cloning the repo, there're one issue emerged:

As windows does not allow file name to contain "|", all the `.png` file under `haldcluts` cannot be cloned:

![image](https://user-images.githubusercontent.com/1921878/203942017-449b2754-1bbf-4f07-be42-212645240015.png)

Would it be possible to rename the file on your side so that this repo can be cloned as a "cross-platform" one?

**Comment by t3mujin** [comment]
Hi! Let me get into it.
