### ISSUE TITLE
Uninstall script in Mac

### ISSUE THREAD

**Issue by t3mujin** [t3mujin/t3mujinpack#4]
Current install script does not work in Mac, "which darktable" throws an error. All the rest works alright.

**Comment by albertogg** [comment]
I just spotted this too, for some reason there's no `darktable` command. I have not used Darktable for too long (since version 2.2.2) and I don't know if the command line was there before.

**Comment by adamhsparks** [comment]
Using `mdfind` if OS is macOS might work?

_e.g._

```bash
❯ mdfind darktable.app                                                                                               
/Applications/darktable.app
```

**Comment by t3mujin** [comment]
@adamhsparks Honestly don't know, I'm unable to test and I haven't used that much MacOS

**Comment by adamhsparks** [comment]
How can I help?

That’s the output I get when I run that command. It finds it. 

I might be able to modify and test the script. I started to but got side tracked editing photos and working on an R package.

**Comment by adamhsparks** [comment]
Ah. Yes. Let me see what I can do!
