### ISSUE TITLE
Main webpage URL cannot be found anymore

### ISSUE THREAD

**Issue by pierrrrrrre** [t3mujin/t3mujinpack#5]
Hello!

I just heard about this project, but the main page does not work anymore:

https://photos.joaoalmeidaphotography.com/en/t3mujinpack-film-darktable/

Since it's a reference I found on this GitHub project as well as on reddit, Pixl.us and other websites, I think it would be good to put this page back online :)

**Comment by taspts** [comment]
try http://blog.joaoalmeidaphotography.com/en/t3mujinpack-film-darktable/

**Comment by pierrrrrrre** [comment]
Thanks, it works!

The author may want to create a redirection from the old URL to the new. After all, *good URIs don't change* ;)

**Comment by t3mujin** [comment]
Sorry @taspts, recently I did some changes in all my web sites and this was another side effect on this, and the fact I've been very busy with my day work hasn't helped. I tried to setup the redirect but my DNS now is based on Cloudflare, and I already ran out of free Page Rules that would allow me to do that, still trying to find a solution though.  

Thanks @pierrrrrrre ! 👍
