### ISSUE TITLE
Film suggestion: Fuji Fortia 50

### ISSUE THREAD

**Issue by mberg2007** [t3mujin/t3mujinpack#7]
Saw some sample images shot with this film and was kind of intrigued. Nothing urgent just a suggestion for a new type of film :-)

https://en.wikipedia.org/wiki/Fortia_SP

**Comment by t3mujin** [comment]
Thanks! Do you have any samples? Either your own pictures of links

**Comment by mberg2007** [comment]
I'm afraid I don't have samples as I shoot only digital, but there are some available on Flickr. Here's a link to the Fortia group:

https://www.flickr.com/groups/fujifortiasp/

I also found this article which goes into more detail about the characteristics of this particular slide film:

http://photographyri.com/?p=237

And another user with his observations:

https://dreaming-artemis.com/2008/03/04/fujifilm-fortia-sp-50/

It might be worth reaching out to either of these two to get some quality scans in case you decide to add this film.

The reason I think this is a cool film is because it is so over the top saturated, like boosted Velvia almost. It gives a very unique look and would be great for certain types of landscape photography.

**Comment by t3mujin** [comment]
Just added it.

**Comment by mberg2007** [comment]
Thanks a lot - Looks great! :-)
